### ISSUE TITLE
Combobox: Escape key should not clear current input

### ISSUE THREAD

**Issue by eldargab** [w3c/aria-practices#1066]
Currently ARIA 1.1 Combobox example says about ESC key that it:

* Clears the textbox
* If the listbox is displayed, closes it.

To my feeling textbox clearing contradicts almost everything users are used to and expect.

1. Escape key usually means "Abort what you are currently doing". From that point of view clearing is definitely an unwanted side effect.

2. Native browser select does not clear selection on escape key.

3. Every UI library I am aware of, which implements combobox pattern, does not clear textbox as well. [Ant design](https://ant.design/components/select/), [react-select](https://react-select.com/home), [select2](https://select2.org) to name a few and those are very popular.

### to-do list added by Matt

This will be fixed in APG 1.2 with the following:

- [x] Fixed in pattern with commit 315a4dd
- [x] Fixed in combobox-autocomplete-both.html with commit 85085b2
- [x] Fixed in combobox-autocomplete-list.html with commit 85085b2
- [x] Fixed in combobox-autocomplete-none.html with commit 85085b2
- [ ] Fix in grid-combo.html

**Comment by smhigley** [comment]
I agree, I think this might also get in the way of 1.4.13/Content on hover or focus, since it's currently not possible to enter a value in the input without keeping the menu open.

**Comment by mcking65** [comment]
Commit 315a4dd fixed this in the pattern but not in the examples.

**Comment by mcking65** [comment]
Sarah, thank you for the fabulous review.

@smhigley wrote:

> * NVDA + Firefox: reads the page title four times almost every time I change options using the arrow key with the listbox open (this may be related to the fact that all option elements are mutated every time one changes selection; I'd be happy to investigate the root cause further). This is a code bug, not an issue with the pattern, as it did not repro in a different implementation.
> * JAWS + Firefox: would sporadically re-announce the listbox when arrowing through options. Seems likely related to the above

Opened #1264 and scheduled to resolve in next milestone.

> * IE: none of the listbox comboboxes work at all, with or without screen readers running

I didn't open an issue for this since we previously discussed dropping IE support in the new year.

> * IE: the grid combobox does not work with JAWS; options are not read when arrowed to.

Known bug in JAWS support for grids.

> * macOS + VoiceOver: the suggested "open" keyboard command does not work (Caps + Space), though Option + down arrow does
> * macOS + VoiceOver: although everything but Caps+ Space worked for me in 10.14, @jnurthen reported that 10.15 did not work; someone else with Catalina should probably officially test this.

My system is still 10.4.6, and it works for me too. We will need to continues this testing prior to APG 1.2 R1.

> * iOS + VoiceOver: the "open" button did not work (didn't open the listbox, and sent the cursor back to the text input). I'd suggest either making the open button `aria-hidden="true" tabindex="-1"`, or removing it altogether.

Surprising suggestion. How would touch users expand/collapse the combobox if it is not accessible?

This is a widget that we should make touch compatible before APG 1.2 release. Opened #1267.

> * Windows high contrast mode: the selected option within the listbox is not visible

Added this to issue #1263.

> General functionality notes and issues:
> 
> * The listbox/grid popup does not close when clicking outside of it (detailed comment on why in the `combobox-list.js` file)

Opened #1265 and scheduled for next milestone.

> * Escape clears the text input (this has been mentioned before). It also means that if you have a currently selected item and open the listbox, it's impossible to dismiss the listbox and restore the original selection with escape

Added to #1066.

> * Grid combobox: it seems odd that this combobox (and only this one) does not let you open the popup and see all options without first typing something
> * This isn't fully a bug, but I find it odd that the list scrolls every time you navigate to a new option, even if that option was already in view before the programmatic scroll

Opened #1266 and schedule for next milestone.

**Comment by jongund** [comment]
@mcking65 I is the guidance for Escape key be close the listbox, if open, and the value of the textbox should just be the characters they have typed into the textbox?
