### ISSUE TITLE
Review Navigation Treeview Example Using Computed Properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#225]
All clean up of the [Navigation Treeview Example Using Computed Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html) is complete and it is ready for final task force review.

#### Task Force Member Reviews Requested as of Nov 20, 2017

- [x] Review by Ann (@annabbott)
- [ ] Review by Siri (@shirsha)
- [x] Review by Evan (@sh0ji)

#### Required Updates

- [x] Editorial clean up
- [x] Issue #364: Navigation Tree View examples: enter key and modifier keys are not correctly handled
- [x] Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior
- [x] Issue #404: Disable default focus ring and implement hover and focus states in css
- [x] Issue #406: Plus/Minus characters are being read by screen readers 
- [x] Issue #712: Treeview Examples: Hovering to right of tree causes blinking

**Comment by annabbott** [comment]
In the Keyboard Support section, currently the following is listed:
Home Moves focus to first node.
End Moves focus to the last node that can be focused without expanding any nodes that are closed.

Question: does Home expand any nodes that are closed?

Also, none of the links with role="treeitem" causes a page to load either via keyboard or mouse.

**Comment by mcking65** [comment]
Two more issues that need to be resolved before we can complete this review:

1. Issue #364: Navigation Tree View examples: enter key and modifier keys are not correctly handled
2. Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by mcking65** [comment]
This issue is now dependent on issues #365, #385, and #386.

**Comment by annabbott** [comment]
Keyboard Support  > last row:
Shows an asterisk character, which for low vision users could be mistaken for a spot of dust on the screen.

Suggest adding "(asterisk)" without the double quotes after the character for clarity.

**Comment by annabbott** [comment]
No other issues noted.

**Comment by sh0ji** [comment]
The `hover` class is being added and removed very rapidly when hovering over the `[role=treeitem]`'s section that is outside the width specified in the corresponding CSS selector. The result for the user is white/gray flashing that exceeds 3 flashes per second.

This appears to be because the corresponding span (`firstElementChild` of the tree item) is full-width on mouseover, and then CSS immediately sets it to `16em`, triggering the mouseout event.

```css
[role="treeitem"].hover,
[role="treeitem"] span.hover {
  background-color: #DDDDDD;
  /* this causes the hover class to be removed if the cursor is outside the 16em */
  width: 16em;
}
```

**Comment by mcking65** [comment]
Closing with all review issues resolved.
