### ISSUE TITLE
Review Navigation Treeview Example Using Declared Properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#226]
This issue is for collecting feedback on and tracking editorial revisions to the 
[Navigation Treeview Example Using Declared Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html).

#### Required Updates

- [x] Editorial cleanup
- [x] Issue #364: Navigation Tree View examples: enter key and modifier keys are not correctly handled
- [x] Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior
- [x] Issue #385: fix incorrect right arrow behavior 
- [x] Issue #386: Unused treeitemClick.js file

**Comment by carmacleod** [comment]
Typo: compuuted

**Comment by carmacleod** [comment]
The tree is a keyboard trap, i.e. can't tab out of it.

**Comment by carmacleod** [comment]
Ctrl+click on link (which opens link in new tab) should not collapse tree.

**Comment by carmacleod** [comment]
Links in tree need to support keyboard shortcut Shift+F10 to bring up context menu.

**Comment by carmacleod** [comment]
The entry for the Space key behavior says, "Performs the default action (e.g. onclick event) on the current treeitem, in this example updating the "File or Folder Selected" textbox."
However, for this example, the default action for a "branch" treeitem is expand/collapse, and the default action of a "leaf" treeitem is to open the link.

**Comment by carmacleod** [comment]
Typo: "relies on the browser to computer values"
should be: "relies on the browser to compute values"

**Comment by carmacleod** [comment]
Typo: "his example implements "
should be: "This example implements "

**Comment by carmacleod** [comment]
For left arrow when focus is on a child node that is also an end node, did you intend to close the parent node after moving focus to it? In other words, the APG says left arrow on a leaf should move focus to the parent, but the APG does not say to then collapse the parent. It feels a bit unexpected in this example to have the parent collapse when I am just navigating left.

**Comment by carmacleod** [comment]
Typo in the right arrow function description: "For a treeitem is in the expanded state"
should be: "For a treeitem that is in the expanded state"

**Comment by carmacleod** [comment]
I find the description of the * (asterisk) behavior somewhat confusing.
It currently says: "Opens all the expandable treeitems in the current leaf (e.g. siblings of the current treeitem)"
Can we change it to: "Opens all expandable treeitems that are siblings of the current treeitem"?

**Comment by carmacleod** [comment]
In the ARIA Roles, Properties and States table, the Usage notes for the tree role say, "Accessible name for the tree widget comes from aria-label attribute."
However, it should say, "Accessible name for the tree widget comes from aria-labelledby="tree1" attribute."

**Comment by carmacleod** [comment]
Typo in the third Usage note for tree role: "the ul[role"tree"] element "
should say: "the ul[role="tree"] element "

**Comment by carmacleod** [comment]
Since the tree (ul) is using aria-labelledby instead of aria-label, the Usage note for aria-label="string" should be for aria-labelledby="id". (in this case, the id is "tree1").

**Comment by carmacleod** [comment]
Typo in the fourth Usage note for group role: "the ul[role"group"] element "
should be: "the ul[role="group"] element "

**Comment by carmacleod** [comment]
Typo  in the first Usage note for treeitem role: 
"The role="treeitem" attribute identifies the li element as an ARIA tree widget."
should be:
"The role="treeitem" attribute identifies the li element as an ARIA treeitem widget."

**Comment by carmacleod** [comment]
Here's a quibble: Is a treeitem really a widget? I think of the tree as being the widget, and the treeitems are just treeitems. So, for example, in the previous comment, I would just say,
"The role="treeitem" attribute identifies the li element as an ARIA treeitem."
If we decide to change this, please note that the phrase "treeitem widget" appears 7 times on this page.

**Comment by carmacleod** [comment]
Just FYI, this example doesn't work well in VoiceOver/Safari, which is probably something that Apple needs to fix. (You may have already opened a radar for this).
Symptoms are:
- VO thinks the widget is a table (even though the code clearly says role="tree")
- VO doesn't speak the leaves at all (i.e. if you arrow to the anchors, VO says nothing)

**Comment by annabbott** [comment]
Deferring to Carolyn's extensive comments.

**Comment by mcking65** [comment]
Two more issues that need to be resolved before we can complete this review:

1. Issue #364: Navigation Tree View examples: enter key and modifier keys are not correctly handled
2. Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by mcking65** [comment]
This issue is now dependent on issues #365, 385, and #386.

**Comment by mcking65** [comment]
Since all feedback raised in this issue is addressed, and since there are many comments, closing this issue. Will open a fresh  issue to complete the review process.
