### ISSUE TITLE
Review Layout Grid Examples

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#227]
The 
[Layout Grid Examples](http://w3c.github.io/aria-practices/examples/grid/LayoutGrids.html) 
are ready for review. Please look for both editorial and functional issues. If testing with a screen reader, keep in mind that screen reader support for grids remains incomplete. While they can be used with any screen reader, screen readers do not yet speak all the information needed for any user to make full use of the grid widgets.

#### Task Force Reviews Request as of October 11, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Bryan (@accdc)
- [x] Review by Jemma (@a11ydoer)
- [x] Review by Siri (@shirsha)

**Comment by annabbott** [comment]
In Example 1, the link to "SVG 2 Specification" needs to be updated to the current version of that spec at https://www.w3.org/TR/SVG2/

**Comment by annabbott** [comment]
In Example 1 > Notes:
The secondary numbered list under Number 1 should be a bulleted list of regular solid bullets.

**Comment by annabbott** [comment]
In Example 2 > Notes:
The bullets should be regular solid bullets instead of hollow bullets.

**Comment by annabbott** [comment]
In Other Features > numbered list at end:
The bullets should be regular solid bullets instead of hollow bullets.

**Comment by accdc** [comment]
I think these widgets are working as coded, where focus is set to controls inside the gridcell nodes then focus is moved around when the arrow keys are pressed. As mentioned above though the screen reader support is so bad at present that this is nearly impossible to test from an accessibility perspective.

I may be missing it, but one thing I don't see here is an example that follows the 1.0 design pattern paradigm, where focus is moved between the gridcell nodes specifically. This is needed in cases when cells include embedded edit fields and the arrow keys cannot be relied upon to do both switch between cells and also allow cursor navigability within the edit field for editing feedback when typing, using the left and right arrow keys to navigate by character, home and end to move to the end or beginning, and so on when focus is on an edit field.

There are also instances of gridcells that include multiple active elements, such as an edit field and an associated date picker button, both of which are focusable and need to be discoverable within the same cell, so it is necessary to use the arrow keys to navigate to the cell, then enter the cell such as by pressing Enter or Tab to interact with those controls.

Arguably the above example with multiple interactive elements could be more simply implemented as a simple static data table so then users could just use standard table navigation commands to go to that field and interact with them normally, but the same can be said for these other data grids as well.

**Comment by shirsha** [comment]
Unable to close the Grid Instructions (NUX) by selecting the "Close Tutorial" link in IE using keyboard and mouse.
IE version I am having is 11.0.9600.18816

![grid example](https://user-images.githubusercontent.com/7432373/32186556-62c75fa0-bd70-11e7-8565-26e70088b758.png)

**Comment by shirsha** [comment]
For Example 2:
I used NVDA in FF.
I can't navigate between the next and previous logical row using the down or up arrow.
I tried using right and left arrow but can't move from move focus to every element from beginning to end. As a result of this I can't navigate to remove button.

**Comment by a11ydoer** [comment]
@mcking65 I have read through the pattern twice and checked the example but I cannot get clear idea from the spec. Please give me more time to review this Layout grid design. Thanks, Jemma

**Comment by mcking65** [comment]
annabbott commented:

> In Example 1, the link to "SVG 2 Specification" needs to be updated to the current version of that spec at 
> https://www.w3.org/TR/SVG2/

Fixed in commit 517fc96.

@annabbott commented:

> In Example 1 > Notes:
> The secondary numbered list under Number 1 should be a bulleted list of regular solid bullets.
> In Example 2 > Notes > numbered list:
> The bullets should be regular solid bullets instead of hollow bullets.
> In Other Features > numbered list at end:
> The bullets should be regular solid bullets instead of hollow bullets.

In commit 517fc96, Changed to nested ordered lists with `type="A"`.

**Comment by mcking65** [comment]
@accdc commented:

> I may be missing it, but one thing I don't see here is an example that follows the 1.0 design pattern paradigm, where focus is moved between the gridcell nodes specifically. This is needed in cases when cells include embedded edit fields and the arrow keys cannot be relied upon to do both switch between cells and also allow cursor navigability within the edit field for editing feedback when typing, using the left and right arrow keys to navigate by character, home and end to move to the end or beginning, and so on when focus is on an edit field.

Bryan, in these examples, if you put tabindex on the cell and not on something inside the cell, the cell gets focus. However, on this page, the point is to describe how to use grids to group widgets, not for providing editable cell content. 

We will demonstrate editable cells in the advanced data grids. However, an alternative to that is to do what is done in the simple data grids, which is to put a button inside the cell where the button label is the editable value. Activating the button changes the cell to an edit field and pressing enter or escape changes it back to a button.

> There are also instances of gridcells that include multiple active elements, such as an edit field and an associated date picker button, both of which are focusable and need to be discoverable within the same cell, so it is necessary to use the arrow keys to navigate to the cell, then enter the cell such as by pressing Enter or Tab to interact with those controls. 

We will demonstrate that pattern in the advanced data grids. But, when using the grid to group widgets, since you rarely have column and ro headers, it is not necessary to have the same number of cells per row. You could instead, give each focusable element its own cell. For the edit, you could have an editable focusable cell or use the button technique I described above.

The main point here is that the purpose of the underlying grid is to convey the logical relationships and provide logical arrow key navigation. The cells do not have to be arranged in physical rows and columns. So you are not bound to making each "physical block" into a single cell.

> Arguably the above example with multiple interactive elements could be more simply implemented as a simple static data table so then users could just use standard table navigation commands to go to that field and interact with them normally, but the same can be said for these other data grids as well.

I agree static tables would be simpler to implement.

Maybe this page does not do as good a job as I hoped of clearly demonstrating the advantages of grouping widgets with grids.

Static tables would put every element in the tab sequence. If example 1 had 30 links, that would be a truly horrible keyboard experience. If the user made a distribution list of 15 or 50 people in example 2, that would be even more horrific for keyboard users. And, if the set of search results in example 3 were effectively infinite, that would make everything beyond the grid completely inaccessible without some kind of janky skip out link in each search result.

Further, these grouping grids are not tables. They do not have row and column headers. If they were tables, some people would argue they need role presentation. Then, screen reader table nav would evaporate.

Can you suggest how we could modify the page to better communicate these advantages and concepts?

**Comment by mcking65** [comment]
@shirsha commented:

> Unable to close the Grid Instructions (NUX) by selecting the "Close Tutorial" link in IE using keyboard and mouse.
> IE version I am having is 11.0.9600.18816

I opened issue #531 for this.

@shirsha commented:

> For Example 2:
> I used NVDA in FF.
> I can't navigate between the next and previous logical row using the down or up arrow.
> I tried using right and left arrow but can't move from move focus to every element from beginning to end. As a result of this I can't navigate to remove button.

Siri, because NVDA does not yet fully support the grid, you have to manually turn on focus mode with capslock+space when focus is inside the grid. Similarly with JAWS, you need to press insert+z.

**Comment by a11ydoer** [comment]
@mcking65 Here is my comment on design spec first.

1. It would be good if we can use plain language as much as we can. For example, is it necessary to use the word, "nomenclature"? 
2. Difference between grid and table - "Grid has only one focusable element in the page tab sequence" but "All focusable elements contained in a table are included in the page tab sequence". It is sort of understandable but it was not clear to me right away. Are we trying to address "Managing Focus Within Components Using a Roving tabindex" eventually with this page tab sequence distinction?

**Comment by a11ydoer** [comment]
@mcking65 "Example 2: Pill List For a List of Message Recipients" is great - very clear in presenting one of layout grid concepts. Keyboard navigation also works well.

**Comment by a11ydoer** [comment]
@mcking65 Here are my humble suggestions for Example 3 

1. Adding visual context of "search" with 5 results: From the coding,  <div role="grid" aria-label="Search Results" aria-rowcount="19" data-per-page="5" data-wrap-cols="true">, it was clear that the example demonstrate 5 search results in one page from total of 19 search results. However, how about adding visual context of "search" with 5 results? For example, we can add a text, "search results for W3C resources about WAI-ARIA" before /above 5 grid cells. If we want to add more context of search result, even we can add "loading 19 results" even though they are not dynamically generated search results. 
2. Heading structure of "Example 3" is heading level 3 and the each grid cell heading level is also heading level 3. I think grid cell heading level should be either 4 or something since they are part of example 3 block.
3. Title of "Scrollable search result" : I had expected "scrollable" behavior from the grid.  By adding the word "scrollable", do we intend to imply that this is a long list or something else?

**Comment by accdc** [comment]
"Can you suggest how we could modify the page to better communicate these advantages and concepts?"

Not at present, this is also the nature of wireframes.

**Comment by mcking65** [comment]
a11ydoer commented:

> 1. It would be good if we can use plain language as much as we can. For example, is it necessary to use the word, "nomenclature"?

Changed in commit 359bbab.

> 2. Difference between grid and table - "Grid has only one focusable element in the page tab sequence" but "All focusable elements contained in a table are included in the page tab sequence". It is sort of understandable but it was not clear to me right away. Are we trying to address "Managing Focus Within Components Using a Roving tabindex" eventually with this "page tab sequence" distinction?

Changed in commit 085c74a.

> Here are my humble suggestions for Example 3
> 1. Adding visual context of "search" with 5 results: From the coding, it was clear that the example demonstrate 5 search results in one page from total of 19 search results. However, how about adding visual context of "search" with 5 results? For example, we can add a text, "search results for W3C resources about WAI-ARIA" before /above 5 grid cells. If we want to add more context of search result, even we can add "loading 19 results" even though they are not dynamically generated search results.
> 2. Heading structure of "Example 3" is heading level 3 and the each grid cell heading level is also heading level 3. I think grid cell heading level should be either 4 or something since they are part of example 3 block.

Raised issue #544.

> 3. Title of "Scrollable search result" : I had expected "scrollable" behavior from the grid. By adding the word "scrollable", do we intend to imply that this is a long list or something else?

Yes, that it is a long list and only part of it is visible. Tghis will be apparent when issue #544 is resolved.

**Comment by mcking65** [comment]
Thank you everyone for the excellent feedback on this example page. Everything has been addressed with either a commit or a new issue so closing this review.
