### ISSUE TITLE
Review revised Navigation Treeview Example Using Declared Properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#405]
Editorial work on the [Navigation Treeview Example Using Declared Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html) is complete and the example is ready for task force review.

#### Task Force Member Reviews Requested as of Nov 20, 2017

- [x] Review by Ann (@annabbott)
- [ ] Review by Siri (@shirsha)
- [ ] Review by Evan (@sh0ji)

#### Revision to-do list

- [x] Issue #404: Disable default focus ring and implement hover and focus states in css
- [x] Issue #406: Plus/Minus characters are being read by screen readers

**Comment by annabbott** [comment]
Seems to be same page as I reviewed for #225 .

**Comment by mcking65** [comment]
Closing as no issues found.
