### ISSUE TITLE
Review Grid and Table Properties guidance section

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#505]
A draft of the [Grid and Table Properties](http://w3c.github.io/aria-practices/#gridAndTableProperties)
guidance section is ready for review.

#### Task Force Member Reviews Requested as of October 29, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Siri (@shirsha)
- [x] Review by James (@jnurthen)

**Comment by devarshipant** [comment]
Some observations:

**Section 6**
- Refer http://w3c.github.io/aria-practices/#gridAndTableProperties

1.  extra space
> determine :

should be: 
determine:

2.  Possible Rephrasing
> Browsers can automatically calculate dimension information and put it into their accessibility tree based on what is in the DOM.

could be:
Wherever possible, browsers, based on the rendered DOM, automatically calculate dimension information and store it in their accessibility tree.

3.  lower vs. upper case
> additionally, some of this information, like skipped columns or rows and how data is sorted, cannot be derived from the DOM structure.

should be:
Additionally ...

**Section 6.1**
- Refer http://w3c.github.io/aria-practices/#gridAndTableProperties_rows

1. spell check 
>commyunicate and indicies 

should be:
communicate; indices

2.  Item # 3 
> If cells span multiple rows, set to the index of the first row in the span.

should be:
Set to the index of the first row in the span if cells span multiple rows.

3. spell check 
>devastating
  
should be:
devastating 

**Section 6.2**
- Refer http://w3c.github.io/aria-practices/#gridAndTableProperties_cols

1. spell check 
>commyunicate and indicies 

should be:
communicate; indices

2. Item # 3
> If a cell spans multiple columns, set to the index of the first column in the span.

should be:
Set to the index of the first column in the span if a cell spans multiple columns.

**Comment by annabbott** [comment]
All issues have been previously reported.

**Comment by mcking65** [comment]
@devarshipant, @shirsha, and @annabbott, Thank you for the excellent attention to detail.

I have pushed commit 40b6c22 with the following changes.

@devarshipant commented:

> 1. extra space: "determine :" should be "determine:"

Fixed.

> 2. Possible Rephrasing
> > Browsers can automatically calculate dimension information and put it into their accessibility tree based on what is in the DOM.
> could be:
> > Wherever possible, browsers, based on the rendered DOM, automatically calculate dimension information and store it in their accessibility tree.

I changed to: "Browsers automatically populate their accessibility tree with the number of rows and columns in a grid or table based on the rendered DOM."

> 3. lower vs. upper case
> > additionally, some of this information, like skipped columns or rows and how data is sorted, cannot be derived from the DOM structure.
> should be:
> > Additionally ...

Fixed.

> Section 6.1
> 1. spell check: "commyunicate" and "indicies" should be: communicate; indices

Fixed.

> 2. Item # 3

> If cells span multiple rows, set to the index of the first row in the span.
> should be:
> Set to the index of the first row in the span if cells span multiple rows.

Fixed.

> 3. spell check "devistating" should be devastating

Fixed.

> Section 6.2
>
> 1. spell check "commyunicate" and "indicies" should be: communicate; indices

Fixed.

> 2. Item # 3
> > If a cell spans multiple columns, set to the index of the first column in the span.
> should be:
> > Set to the index of the first column in the span if a cell spans multiple columns.

Fixed.

@shirsha commented:

> Apart from the spelling mistakes identified above one more semantic error it in 6.2.2 section it should be: 
> have been scrolled to show (instead of sshow)

Fixed.

**Comment by mcking65** [comment]
Thank you all for the help with this, especially @jongund for the initial draft. Closing as complete!
