### ISSUE TITLE
Review updated introduction

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#519]
In commit d68d78f , I updated the [introduction](http://w3c.github.io/aria-practices/#intro) to:

* Replace link to not-yet-written ARIA background section with link to WAI-ARIA Overview.
* Tighten up phrasing.
* Update  description of the sections of the guide.
* Remove stub appendix section for background on ARIA.

#### Task Force Reviews requested as of Nov 5, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by James (@jnurthen)
- [x] Review by Evan (@sh0ji)

**Comment by sh0ji** [comment]
I have a few editorial/phrasing notes that I can submit a PR for, but I'll discuss them here first:

> WAI-ARIA Authoring Practices is a guide to understanding...

The preposition "for" would work better here: "WAI-ARIA Authoring Practices is a guide **for** understanding..." (emphasis mine).

> With the understanding many prefer to learn from examples, after a brief "Read Me First" section, ...

The "With the understanding..." clause feels unnecessary and awkward here. I recommend simply starting with "After a brief "Read Me First" section, ...".

**Comment by mcking65** [comment]
@sh0ji, I agree that both of your suggestions would be improvements. Go ahead with the PR. Thanks!

**Comment by annabbott** [comment]
No issues noted.

**Comment by jnurthen** [comment]
Reviewed. looks good to me.

**Comment by mcking65** [comment]
Thanks all! We're good to go here. Closing.
