### ISSUE TITLE
Review toolbar example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#539]
#### Update as of Dec 3, 2018

The [toolbar example published in APG 1.1 Release 2](https://www.w3.org/TR/2018/NOTE-wai-aria-practices-1.1-20180726/examples/toolbar/toolbar.html) developed for issue #126 has been redesigned to address the issues listed in the below redesign checklist.

## Preview new toolbar in feature branch

The [redesigned toolbar in feature branch issue541-toolbar-redesign](https://raw.githack.com/w3c/aria-practices/issue541-toolbar-redesign/examples/toolbar/toolbar.html) is ready for review and will be merged to master after issues from this review are resolved.

#### Toolbar Redesign Checklist

- [x] Issue #540: Toolbar Example: aria-selected should not be used
- [x] Issue #541: Toolbar Example: Use button elements and add other types of elements, such as link and checkbox
- [x] Issue #847: Bugs with keyboard support, aria-disabled, and aria-label
- [x] It's hard to tell the difference between checked and not-checked toggles and radios (Noted by @carmacleod in PR #887).
- [x] Add a title/tooltip to the Bold, Italics, Underline, Align left/center/right, Font type, and size increment/decrement tools (for consistency with Cut/Copy/Paste, and in case any sighted folks need help understanding the icons) (Noted by @carmacleod in PR #887).
- [x] Implement menuitemradio elements as radio elements per issue #949.

**Comment by jkva** [comment]
This is my first review within the APG; please let me know I'm not following correct review protocol.

The toolbar items within the toolbar are `div` elements with a `role` of `button` - why are these not `button` elements with a type of `button`?

In `toolbar.js`, specifically `aria.Toolbar.prototype.registerEvents`, the event handlers are explicitly bound via `.bind(this)` while the call site is already determined by the call to `addEventListener()`. Am I missing something here?

**Comment by mcking65** [comment]
Job, thank you for the review. This is exactly the kind of feedback we would like.

@jkva commented:

> The toolbar items within the toolbar are div elements with a role of button - why are these not button elements with a type of button?

Probably because I didn't request it to be done that way when @tatermelon did the original coding work. However, given our overall guidance to prefer native HTML where possible while illustrating important features of the pattern, this is a good suggestion.
I have updated issue #541 to capture this enhancement.

**Comment by jnurthen** [comment]
Adding me to review - I have comments on this.

**Comment by annabbott** [comment]
Accessibility Features
- When tabbing into the toolbar, focus returns to the control that last had focus. Focus movement inside the toolbar is managed using roving tabindex.

I believe that sentence refers to a second pass into the toolbar. 

Suggested edit:
"When tabbing into the toolbar for a second time, "

**Comment by annabbott** [comment]
Accessibility Features
2. Since there is only a single disabled control, to ensure screen reader users are aware of its presence, it is focusable. For additional guidance, see Focusability of disabled controls.

There seems to be five disabled controls (Tool 1 through Tool 5), not a single disabled control.

**Comment by annabbott** [comment]
No other issues noted.

**Comment by spectranaut** [comment]
Hi @tatermelon -- I'm writing tests for this example right now, and I have two questions about the documentation:
1. The attributes table lists `aria-disabled` -- but I couldn't discover a way to disable one of the toolbar element (by which I mean, it seems as though `aria-disabled` is never set on any element of the toolbar). Is there a way to disable elements? Should this row just not be included?
2. The attributes table makes me think the `aria-label` element belongs on div with `role="toolbar"` -- but it is instead on the `role="separator"` div, is this intentional?

**Comment by spectranaut** [comment]
Hi @tatermelon -- while writing tests for the other attributes and keys, I also noticed these two inconsistencies with the table documentation:
1. The "right arrow" and "left arrow" keys do not cycle though the tools -- a "right arrow" to the last element in the toolbar does not move the focus to the first element in the toolbar, for example.
2. the "home" and "end" keys do not move the focus in the toolbox

**Comment by tatermelon** [comment]
Hey @spectranaut, @mcking65 is the one who wrote the documentation for the examples, so he will know better which is correct. @mcking65 should the example be updated to match the attribute table or should the attribute table be updated to match the way the example is working?

**Comment by SuzanneTaylor** [comment]
When focus is on any of the first five buttons, if you press space-bar to activate the button, the default action of the space-bar still happens, and the page scrolls. The buttons have no implemented action and so testing and development didn't explore this far, but in terms of having an example we can send people to that covers all common mistakes, it would good to implement some simple function for the buttons and then illustrate .preventDefault()

**Comment by mcking65** [comment]
Thank you @SuzanneTaylor, I agree. I've added this to issue #847.

**Comment by mcking65** [comment]
A [redesigned toolbar](https://raw.githack.com/w3c/aria-practices/issue541-toolbar-redesign/examples/toolbar/toolbar.html) is ready for review in the issue541-toolbar-redesign feature branch.

**Comment by mcking65** [comment]
In today's APG task force meeting, Michiel posted some useful images during the discussion about making the pressed state of buttons more visually distinct from the not pressed state.

>jn: border is fine as long as there is a 3:1 ratio
>... border isn't dark enough - is only 2:1
>MichielBijl:
>https://usercontent.irccloud-cdn.com/file/SMBtoImM/Screenshot%202018-12-03%20at%2020.00.15.png
>https://usercontent.irccloud-cdn.com/file/0iW53xB7/Screenshot%202018-12-03%20at%2020.01.55.png
>image 1: Current situation
>image 2: Preferred situation where the buttons look like one whole group thing

cc: @jongund

**Comment by carmacleod** [comment]
@mcking65 @jongund I like @MichielBijl's suggestion of making the radio buttons look like "one whole group thing" - this is great to show that they are a radio group and not just a bunch of unrelated toggle buttons.

However, it is still hard to glance at the toolbar and know which tools are selected/checked/on. The unselected white #FFFFFF background is just way too close to the selected light-light-gray #F4F4F4 background. I realize these 2 colors don't actually touch because there's a border between them. But I look at that radiogroup and I see 3 whitish-greyish radio button tools, and I have to stare at it to be sure which one is selected. Maybe it's my monitor, or maybe it's my eyes. ;)

**Comment by jongund** [comment]
Do you really want bold, italic and underline buttons to have a title attribute or should the title attribute be used for the accessible name instead of aria-label?

**Comment by jongund** [comment]
I have made most of the updates required in this issue, except for the title attributes on all the controls.  I have added two regression tests, there is some flaw in the roving tabindex test code that has left both Evan and I perplexed.   Still trying to figure out what the problem is, but we have two passing tests right now.

**Comment by jongund** [comment]
I have moved my work on this issue to the W3C repository branch:
https://github.com/w3c/aria-practices/tree/issue541-toolbar-redesign 

You can view the latest version of the toolbar at:
https://raw.githack.com/w3c/aria-practices/issue541-toolbar-redesign/examples/toolbar/toolbar.html

**Comment by devarshipant** [comment]
1.  Is aria-controls implemented correctly? In the example, aria-controls IDREF (menu1) points to the `ul`. However, the Usage reads "Provides a reference to the textarea that the toolbar controls."

2. Should the toolbar support Control B / I / U on text highlighted within the `textarea`?

**Comment by jnurthen** [comment]
@devarshipant 
1. The toolbar references the textarea with aria-controls correctly. The menu button also has aria-controls pointing to its menu as specified in the menu button pattern.
2. No - this is a demonstration of toolbar. It is not a fully formed text editor.

**Comment by devarshipant** [comment]
On Mon, Dec 17, 2018 at 5:23 PM James Nurthen <notifications@github.com>
wrote:

> @devarshipant <https://github.com/devarshipant>
>
>    1. The toolbar references the textarea with aria-controls correctly.
>    The menu button also has aria-controls pointing to its menu as specified in
>    the menu button pattern.
>
> Got it, thanks. I thought aria-controls was only being used on the menu
button and textarea was the controlled element. On a different note, I am
not sure if JAWS will work properly on the menu button with aria-controls
as it prompts the user (w/ shortcut keys) to the unopened menu. And that
could be a vendor issue.

**Comment by mcking65** [comment]
The redesigned toolbar example is a very significan and great piece of work by @jongund. I think it will be an especially useful reference as it demonstrates how to resolve many integration issues in an effective manner. It appears that it will also help surface quite a few assistive technology support bugs.

I’ve now finished my final editorial updates to it so it is, I hope, consistent with our style guide and all the applicable design patterns as well as with other examples. Now it is time for the whole task force to really hammer on it and see if we missed anything important:
* Are there any bugs? We need testing with latest versions of:
   * Firefox on Windows
   * Chrome on both Win and Mac
   * Safari on Mac (iOS is also informative but not essential before release)
   * IE11.
* Are there any accessibility problems?
* Is the documentation accurate and clear?

This is a rather complex example, so I have assigned five people to do formal reviews in PR #950. Please try to complete your review by Thursday Jan 3 so we have enough time to get a fix in by Jan 8 in the event you find a critical problem. Of course, we welcome reviews from anyone. The more hands and brains on it the better.

To make sure we have the browsers covered, it could be helpful if you share with the group what browsers you test with and on which platform.

Example page for review and test:
https://raw.githack.com/w3c/aria-practices/issue541-toolbar-redesign/examples/toolbar/toolbar.html

Please provide feedback in pull request #950

**Comment by mcking65** [comment]
Moving development of regression tests to a separate issue -- #965.

**Comment by mcking65** [comment]
@annabbott, @sh0ji, @shirsha, @charmarkk,

Does the [newly merged toolbar example](http://w3c.github.io/aria-practices/examples/toolbar/toolbar.html) address this item in the to-do list for this issue?

>It's hard to tell the difference between checked and not-checked toggles and radios (Noted by @carmacleod in PR #887).

**Comment by charmarkk** [comment]
@mcking65 I think so, it's rather evident to me.

**Comment by sh0ji** [comment]
Yep, it looks good to me too. I do have a couple points of feedback, though:

* I expect clicking the padding of the toolbar (the gray #ECECEA part) to move focus into the toolbar. I often use my mouse to orient my focus, and then use my keyboard to move around. This isn't strictly a requirement, but I can't be the only one who does this.
* I'd prefer it if all the controls had a descriptive title attribute so that sighted users don't have to infer or discover the function of the controls.

**Comment by mcking65** [comment]
All feedback has been addressed or is logged in a new issue. Thank you everyone for helping make the toolbar example so good!!
