### ISSUE TITLE
Review example of ARIA 1.0 Combobox With List Autocomplete

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#554]
The [ARIA 1.0 Combobox With List Autocomplete Example](http://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html)
developed for issue #99 is ready for review.

#### Task Force Member Reviews Requested as of Nov 29, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Bryan (@accdc)
- [ ] Review by  James (@jnurthen)
- [ ] Review by Job (@jkva)

**Comment by devarshipant** [comment]
The note says:
> If the user types one or more characters in the edit box and the typed characters match the beginning of the name of one or more states or territories, a listbox popup appears containing the matching names. When the listbox appears, a suggested name is not automatically selected. Thus, after typing, if the user tabs or clicks out of the combobox without choosing a value from the listbox, the typed string becomes the value of the combobox.

Questions (tested with IE 11 / JAWS 18): 
1. Should a screen reader announce how many matching names were returned?
2. IE 11 does not show the list of states.

<img width="162" alt="blank droplist" src="https://user-images.githubusercontent.com/7377040/33378350-813647c4-d4e2-11e7-8781-ca1985b1852d.PNG">

**Comment by accdc** [comment]
"1.	Should a screen reader announce how many matching names were returned?"

Either the number of matches or the first suggested match needs to be announced. Otherwise this will not be accessible on touch screen devices because non-sighted users will never be aware that a change has occurred on the screen. Unfortunately nothing exists in the ARIA spec to account for this at a platform API level automatically so it has to be done manually.

I'll be reviewing the live code later today and will provide feedback then.

**Comment by mcking65** [comment]
@accdc commented:

> > 1. Should a screen reader announce how many matching names were returned?
>
> Either the number of matches or the first suggested match needs to be announced. Otherwise this will not be accessible on touch screen devices because non-sighted users will never be aware that a change has occurred on the screen. Unfortunately nothing exists in the ARIA spec to account for this at a platform API level automatically so it has to be done manually.

There is plenty at the platform API level given how this is coded. When the listbox appears and disappears, there are state change events for aria-expanded. When the listbox is visible, the screen reader can easily determine the number of suggestions because the listbox is directly associated with aria-owns. In addition, the screen reader can determine whether or not exploiting these events is appropriate based on the presence of the combobox role and the value of aria-autocomplete.

Now that we have these reference implementations, perhaps we can get screen reader developers to provide more user friendly support.

So, yes, it would be a good idea for screen readers to be more helpful. However, it is up to the screen reader to decide how to be helpful.

That said, authors can choose to enhance the experience with features they believe fill such gaps in assistive technology support. However, a goal of the ARIA practices is to provide assistive technology developers with the reference implementations they need to provide great experiences for each widget based only on the ARIA required by the spec for that widget.

**Comment by accdc** [comment]
"When the listbox is visible, the screen reader can easily determine the number of suggestions because the listbox is directly associated with aria-owns."

This actually brings up a problem that I noticed, which is that the use of aria-owns causes accessibility issues in some AT/browser combos, which is why I argued to change this to aria-controls which actually does work properly. So why should we include aria-owns in this example when it's use has been changed for this role and AT venders have no incentive to ever make this work in the future?

**Comment by mcking65** [comment]
accdc commented:

> the use of aria-owns causes accessibility issues in some AT/browser combos, which is why I argued to change this to aria-controls which actually does work properly. So why should we include aria-owns in this example when it's use has been changed for this role and AT venders have no incentive to ever make this work in the future?

Using aria-controls is at the heart of the ARIA 1.1 pattern.

The ARIA 1.0 spec said to use `aria-owns`. We agreed that we need to be faithful to the 1.0 spec because of the tens of thousands of implementations out there that have used it. You are one of the people who most strongly encouraged this position, and you have been quite convincing on that very point.

Legacy implementation support is the incentive. The three ARIA 1.0 pattern examples are the reference to help the AT vendors do it well.

**Comment by annabbott** [comment]
No issues noted.

**Comment by accdc** [comment]
In testing this, when I type "c" and press down, the listbox appears to be empty and there are no states displayed. Is this an issue in IE11?

**Comment by accdc** [comment]
"The ARIA 1.0 spec said to use aria-owns. We agreed that we need to be faithful to the 1.0 spec because of the tens of thousands of implementations out there that have used it. You are one of the people who most strongly encouraged this position, and you have been quite convincing on that very point."

Indeed, this is a catch twenty two, because when I originally proposed the change to aria-controls it was only to do that and not to throw out the old design pattern all together and recreate everything. I never suggested that the old design pattern be retired, and argued against this.

I'm not trying to rehash an old argument, but the issue I proposed addressing in ARIA 1.1 was to address an issue in the 1.0 spec with the accessibility tree where aria-owns cannot be used on elements that don't support child elements because these child elements are not accessible there, and the change to aria-controls fixes this problem in the accessibility tree.

So I still find all of this rather frustrating, because the purpose of ARIA 1.1 was not to break support of prior implementations but to enhance them, and in this particular case we are forcing a hard line coding requirement on something that is and will likely always be broken in the accessibility tree.

This again places me in the position where I have to tell clients to do something different from what the W3C guidance states, because if the W3C guidance is followed it results in a less accessible experience for end users in public environments.

**Comment by devarshipant** [comment]
>@accdc -- In testing this, when I type "c" and press down, the listbox appears to be empty and there are no states displayed. Is this an issue in IE11?

Bryan -- I get similar results in IE11.

**Comment by mcking65** [comment]
This example has been  replaced by the 1.2 version, which uses controls instead of owns. This review issue is now obsolete.
