### ISSUE TITLE
Review Example of ARIA 1.0 Combobox without Autocomplete

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#555]
The 
[ARIA 1.0 Combobox without Autocomplete Example](http://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-none.html)
developed for issue #99 is ready for review.

#### Task Force Member Reviews Requested as of Nov 29, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Bryan (@accdc)
- [ ] Review by  James (@jnurthen)
- [ ] Review by Job (@jkva)

**Comment by annabbott** [comment]
No issues noted.

**Comment by accdc** [comment]
For this one, it looks like the use of aria-autocomplete or lack of its use doesn't match the focus functionality.

When aria-autocomplete is not present or set to "none", then when the associated control such as a listbox is rendered then focus should move into the listbox in the same manner as a standard ARIA Listbox widget, which should manage its own focus movement such as by moving focus between the role=option nodes or by setting focus to role=listbox and using aria-activedescendant to referenced this highlighted role=option element when arrowing. Then when the popup widget is closed, whether by canceling or pressing Enter or Alt+Uparrow to choose the highlighted option, then focus should be set back to the role=combobox edit field.

Only when aria-autocomplete is set to "list" should aria-activedescendant be used to simulate focus within an associated widget.

The 1.0 spec states the following for this implementation:

"• If an author sets a combobox's value of aria-autocomplete to 'none' (default), authors MUST manage and set focus on the associated listbox, so assistive technologies can follow the currently selected value."

**Comment by mcking65** [comment]
This example has been  replaced by the 1.2 version, which uses controls instead of owns. This review issue is now obsolete.
