### ISSUE TITLE
Review example of table design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#566]
The [table example page](http://w3c.github.io/aria-practices/examples/table/table.html)
completed for issue #242 is ready for review.

#### Task Force Member Reviews Requested as of December 6, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Jemma (@a11ydoer)
- [x] Review by James (@jnurthen)

**Comment by annabbott** [comment]
No issues noted.

**Comment by a11ydoer** [comment]
Visual styling(CSS) is applied and this example is done!

**Comment by jha11y** [comment]
The current example does not work with Firefox 68.0.1 and NVDA 2019.1.1 when using table reading keystrokes.  NVDA only can navigate the column header row and first data row.

This seems to be because of the combined use of both role="rowgroup" and role="row".  Removing the role="rowgroup" seems to fix the issue.

Steps to reproduce:

1. Go to example page
2. Navigate to second row in table (starts with "Fred")
3. try to use table reading keystrokes to navigate the table (Ctrl+ Alt and arrows keys)

**Comment by mcking65** [comment]
@jha11y commented:

> The current example does not work with Firefox 68.0.1 and NVDA 2019.1.1 when using table reading keystrokes. NVDA only can navigate the column header row and first data row.
> 
> This seems to be because of the combined use of both role="rowgroup" and role="row". Removing the role="rowgroup" seems to fix the issue.
> 
> Steps to reproduce:
> 
> 1. Go to example page
> 2. Navigate to second row in table (starts with "Fred")
> 3. try to use table reading keystrokes to navigate the table (Ctrl+ Alt and arrows keys)

The rowgroup role is used correctly in the example. Since it works with JAWS and Firefox 68, this is most likely an NVDA bug. This is the type of issue we intend to capture and report with the [w3c/aria-at](https://github.com/w3c/aria-at/) project.
