### ISSUE TITLE
Draft guidance section on labeling and describing

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#74]
This section will cover the following:

- [ ] aria-label
- [ ] aria-labelledby
- [ ] aria-describedby
- [ ] aria-details (also see #70)
- [ ] Possibly aria-placeholder
- [ ] aria-roledescription (also see #651)
- [ ] Accessible name calculation
- [ ] Elements named from content vs named by author
- [ ] Effect of aria-owns on name calculation determined in issue #277 
- [ ] Accessible description calculation

For reference, content of a draft labeling and describing section from a very old APG working draft has been preserved [here](https://raw.githack.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#relations_labeling).

**Comment by mcking65** [comment]
In the August 25, 2016 ARIA call, there was discussion about creating a table of roles that shows for each:
1. Name from author: yes/no
2. Name from content: yes/no
3. Name required: yes/no

Our labeling and describing section should explain, as simply as possible, what the various possible combinations of values for named from author and named from content mean. 

One issue discussed in the ARIA call is that authors frequently label things that are named from content, which is unnecessary if the content provides a good label.

Shane has a script that could auto generate the table for our labeling and describing section.

**Comment by jnurthen** [comment]
Include #651

**Comment by mcking65** [comment]
Complete with commit 37da361.

The new section on [providing accessible names and descriptions](http://w3c.github.io/aria-practices/#names_and_descriptions) is now in the editor's draft.
